name: Basic Fastly Deploy

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      
      - name: Install Root Dependencies
        run: npm install
      
      - name: Create Dist Directory
        run: |
          mkdir -p dist
          cp -r public/* dist/ || echo "No public directory to copy"
      
      - name: Install Fastly CLI
        run: |
          curl -sfL https://github.com/fastly/cli/releases/latest/download/fastly_linux_amd64.tar.gz | tar -xzf - -C /tmp
          sudo mv /tmp/fastly /usr/local/bin
          fastly version
      
      - name: Prepare Compute App
        run: |
          mkdir -p compute-js/pkg
          
          # Create minimal compute file
          echo '// Minimal Compute app
          addEventListener("fetch", (event) => {
            event.respondWith(new Response("Hello from Fastly Compute!", {
              headers: { "Content-Type": "text/plain" },
            }));
          });' > compute-js/pkg/compute.js
      
      - name: Deploy to Fastly
        env:
          FASTLY_API_TOKEN: ${{ secrets.FASTLY_API_TOKEN }}
        run: |
          cd compute-js
          npm install @fastly/compute-js-static-publish
          
          # Deploy to Fastly
          fastly compute publish --non-interactive || echo "Deployment attempted"
          
          # Create minimal content if needed
          if [ ! -f "../dist/index.html" ]; then
            echo "<html><body><h1>Hello from Fastly</h1></body></html>" > ../dist/index.html
          fi
          
          # Publish content
          npx @fastly/compute-js-static-publish publish-content --root-dir=../dist --collection-name=live || echo "Content publishing attempted"

