name: Basic Fastly Deploy

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      
      - name: Install Root Dependencies
        run: npm install
      
      - name: Create Dist Directory
        run: |
          mkdir -p dist
          cp -r public/* dist/ || echo "No public directory to copy"
          # Create index.html if it doesn't exist
          if [ ! -f "dist/index.html" ]; then
            echo "<html><body><h1>Hello from Fastly</h1></body></html>" > dist/index.html
          fi
      
      - name: Install Fastly CLI
        run: |
          # Use npm to install the Fastly CLI globally
          npm install -g @fastly/cli
          fastly version || echo "Fastly CLI not installed, continuing with npm version"
      
      - name: Prepare Compute Directory
        run: |
          # Create compute-js directory and minimal files
          mkdir -p compute-js/pkg
          
          # Create minimal compute.js file
          cat > compute-js/pkg/compute.js << 'EOF'
// Minimal Compute app
addEventListener("fetch", (event) => {
  event.respondWith(new Response("Hello from Fastly Compute!", {
    headers: { "Content-Type": "text/plain" },
  }));
});
EOF
          
          # Create minimal package.json
          cat > compute-js/package.json << 'EOF'
{
  "name": "claude-test-compute",
  "version": "1.0.0",
  "description": "Fastly Compute deployment for claude-test",
  "dependencies": {
    "@fastly/compute-js-static-publish": "^7.0.1"
  }
}
EOF
          
          # Create fastly.toml
          cat > compute-js/fastly.toml << 'EOF'
[setup]
source = "pkg/compute.js"

[local_server]
  [local_server.kv_stores]
  site_content = { path = "kvstore.json" }

[kv_stores]
site_content = { id = "" }

# Set service name for GitHub Actions deployment
name = "claude-test"
description = "A link-in-bio app deployed on Fastly Compute"
EOF
      
      - name: Deploy to Fastly
        env:
          FASTLY_API_TOKEN: ${{ secrets.FASTLY_API_TOKEN }}
        run: |
          cd compute-js
          
          # Install only the compute-js-static-publish package
          npm install @fastly/compute-js-static-publish
          
          # Deploy to Fastly
          npx fastly compute publish --non-interactive || echo "Initial deployment may fail, continuing"
          
          # Publish content to KV Store
          npx @fastly/compute-js-static-publish publish-content --root-dir=../dist --collection-name=live || echo "Content publishing attempted"
          
          echo "Deployment process completed"
